apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: message-broker-consumer:latest
          imagePullPolicy: Never
          stdin: true
          tty: true
          env:
            - name: CHANNEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: consumer-config
                  key: CHANNEL_NAME
