apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
  namespace: message-broker
spec:
  template:
    spec:
      containers:
      - name: consumer
        image: message-broker-consumer:latest
        imagePullPolicy: Never
        tty: true
        stdin: true
      restartPolicy: Never
