apiVersion: apps/v1
kind: Deployment
metadata:
  name: msgbroker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msgbroker
  template:
    metadata:
      labels:
        app: msgbroker
    spec:
      containers:
      - name: msgbroker
        image: msgbroker-app
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: msgbroker-service
spec:
  selector:
    app: msgbroker
  ports:
  - name: rest-api
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: msgbroker-communication
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
